const keys = {
  INVITE_FRIENDS_PLAN_TRIP: "inviteFriendsAndPlanTrip",
  TO_WHERE_QUESTION: "toWhereQuestion",
  UPDATE_LOCAL_DATE: "updateLocalDate",
  WHO_IS_GOING_QUESTION: "whoIsGoingQuestion",
  CONTINUE: "continue",
  ACCEPT_PRIVACY_AND_POLICY_TERMS: "acceptPrivacyAndPolicyTerms",
  USE_TERMS_AND_PRIVACY_POLICY: "useTermsAndPrivacyPolicy",
  WHEN_QUESTION: "whenQuestion",
  CONFIRM_TRIP: "confirmTrip",
  SELECT_DATE: "selectDate",
  SELECT_DATES_INFO: "selectDatesInfo",
  CONFIRM: "confirm",
  UNTIL: "until",
  OF: "of",
  TRIP_DETAILS: "tripDetails",
  INPUT_ALL_INFO_TO_CONTINUE: "inputAllInfoToContinue",
  DESTINATION: "destination",
  ERROR_AT_LEAST_4_CHAR: "errorAtLeast4Char",
  SELECT_GUESTS: "selectGuests",
  GUESTS_INFO: "guestsInfo",
  TYPE_GUEST_EMAIL: "typeGuestEmail",
  NEW_TRIP: "newTrip",
} as const;

export default keys;
